#!/bin/sh

CUR_DIR=`dirname $0`
CUR_DIR=`pwd $CUR_DIR`
cd $CUR_DIR

ORIG_NAME="rrdtool-1.2.27/"
NAME="python26-rrdtool"
RELEASE=1
PACKAGER="Nick Bailey - nick@riptano.com"
REQUIRES=""
BUILD_REQUIRES=""

# copy to a directory for building
cp -r $ORIG_NAME $NAME/

#have to build rrdtool first
cd $NAME
./configure
make
cp -r src bindings/python/
cd ..

#apply any patches
for patch_file in patches/*
do
    patch -p1 -d $NAME < $patch_file
done

# build rpms
cd $NAME/bindings/python
python2.6 setup.py bdist_rpm \
        --python="python2.6" \
        --dist-dir="$CUR_DIR" \
        --release="$RELEASE" \
        --packager="$PACKAGER" 
cd ..

rm -rf "$CUR_DIR/$NAME"

